version: 2
updates:
  - package-ecosystem: pip
    directory: /
    schedule:
      interval: daily
    groups:
      - development-dependencies:
          patterns:
            - "*"
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: daily
    groups:
      update-types:
        - minor
        - patch
