version: 2
updates:
  - package-ecosystem: pip
    directory: /
    schedule:
      interval: daily
    groups:
      python-packages:
        patterns:
          - "*"
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: daily
    groups:
      npm-packages:
        patterns:
          - "*"
