version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
        schedule:
      interval: "daily"
    groups:
       - development-dependencies:
          patterns:
          - "*"

  - package-ecosystem: "npm" # See documentation for possible values
    directory: "/" # Location of package manifests
    schedule:
      interval: daily
    groups:
      update-types:
      - "minor"
      - "patch"
      

