name: Send GoodMorning Post

on:
    workflow_dispatch:

    schedule:
        - cron: "45 5 * * *"

jobs:
    post:
        runs-on: ubuntu-latest
        steps:
            - uses: shy/bluesky-post@v.1
              with:
                  text: "Good Morning! https://shy.dev/images/GOODMORNING.png"
                  imageURL: "https://shy.dev/images/GOODMORNING.png"
                  identifier: ${{ secrets.BLUESKY_IDENTIFIER }}
                  password: ${{ secrets.BLUESKY_PASSWORD }}
