name: Bluesky Good Morning

on:
  workflow_dispatch:

  schedule:
    - cron: "45 12 * * *"

jobs:
  post:
    runs-on: ubuntu-latest
    steps:
      # You must checkout resources
      - uses: actions/checkout@v3

      - uses: myConsciousness/bluesky-post@v5
        with:
          text: "Good Morning!"
          media: .github/workflows/GOODMORNING.png
          media-alt: "Good Morning!"
          identifier: ${{ secrets.BLUESKY_IDENTIFIER }}
          password: ${{  secrets.BLUESKY_PASSWORD }}
